# Generated by Django 3.1.4 on 2021-01-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201223_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
